### Load libraries
---
execute:
  warning: false
  message: false
---

run api client
```{r}
library(tidyverse)
library(httr)
library(jsonlite)
```
### Run API client
```{r}
url <- "https://api.themoviedb.org/3/authentication"

response <- VERB("GET", url, add_headers('Authorization' = 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhYjczMmU4NzhiZWVkYzMxYzNiN2Y3MDJhZWFmMDcxYyIsIm5iZiI6MTczMzM1MDcyMi4xOTYsInN1YiI6IjY3NTBkNTQyNWFjZTk4YmE0NmQ0ODU5NyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.9LGR9bjTfxEoEGfSv0con3tA9yBuRpNSpFnTDb1jUkA'), content_type("application/octet-stream"), accept("application/json"))

content(response, "text")
```

### Load in Kaggle dataset of Oscar nominees from 1927-2024
```{r}
oscar_nominees <- read.csv("the_oscar_award.csv")
```

### Search for a movie given title and year
```{r}
library(jsonlite)

# function to search for a movie by title and year
search_movie <- function(movie_title, year) {
  url <- "https://api.themoviedb.org/3/search/movie"
  
  # parameters for the query
  queryString <- list(
    query = movie_title,
    year = as.character(year)
  )
  
  response <- GET(url, query = queryString, 
                  add_headers('Authorization' = 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhYjczMmU4NzhiZWVkYzMxYzNiN2Y3MDJhZWFmMDcxYyIsIm5iZiI6MTczMzM1MDcyMi4xOTYsInN1YiI6IjY3NTBkNTQyNWFjZTk4YmE0NmQ0ODU5NyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.9LGR9bjTfxEoEGfSv0con3tA9yBuRpNSpFnTDb1jUkA'),
                  content_type("application/octet-stream"),
                  accept("application/json"))
  
  # check for response status
  if (http_error(response)) {
    stop("Failed to retrieve movie data. HTTP Status: ", status_code(response))
  }
  
  # parse json
  response_content <- content(response, "text")
  json_data <- fromJSON(response_content)
  
  # return the top movie hit
  if (length(json_data$results) > 0) {
    return(
      as.data.frame(json_data$results |>
        arrange(desc(popularity)) |>
        head(1)
    ))
  } else {
    return(NULL) # No results found
  }
}
```

```{r}
# test case
parasite <- search_movie("Parasite", 2020)
print(parasite)
```

```{r}
# Test case for the movie "Titanic" (1997)
titanic <- search_movie("Titanic", 1997)
print(titanic)
```

```{r}
movie_details <- apply(oscar_nominees, 1, function(row) {
  search_movie(row["film"], row["year_film"])
})

#combine all calls into one df
movie_details_df <- do.call(rbind, movie_details)

movie_details_df
```

```{r}
library(dplyr)
oscar_nominees <- oscar_nominees |> 
  rename(title = film) # change to match movie_details_df, film -> title
```

```{r}
join_oscar <- left_join(oscar_nominees, movie_details_df, by = "title")
join_tmdb <- left_join(movie_details_df, oscar_nominees, by = "title")
# many-to-many is expected, same movie is nominated for diff categories
```
```{r}
library(tidyverse)
library(dplyr)
library(tidyr)
# pivot wider to unnest column 'genre_ids' 

join_tmdb <- join_tmdb |> 
  mutate(genre_ids = ifelse(is.list(genre_ids), genre_ids, list(genre_ids))) |> #make all lists
  unnest_longer(genre_ids) |>  #unlist all
  mutate(value = 1) |>  # add a helper column with 1s
  pivot_wider(names_from = genre_ids, values_from = value, values_fill = 0)
 
#error its too large when unnesting/pivot long LOL 
```

```{r}
write.csv(join_tmdb,"/Users/jazellesaligumba/Desktop/groupB-spotify/tmdb/join_tmdb.csv", row.names = FALSE)
```


work on:
- function to filter top movie (based on popularity?) [done]
- function to 
- rbind all movies with tmdb data
- left join tmdb and kaggle
